// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnKrehqtrR5Op1H3rPRFX-RSbRFZ2wYLE',
    appId: '1:39354146251:web:59656ef5f4436959a76a4e',
    messagingSenderId: '39354146251',
    projectId: 'petkart-74fec',
    authDomain: 'petkart-74fec.firebaseapp.com',
    storageBucket: 'petkart-74fec.appspot.com',
    measurementId: 'G-KN5JEZKSSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsTEX-ep0kpBlnVhJDZQ-ihX_Kb6ZgdR8',
    appId: '1:39354146251:android:e194755b71723284a76a4e',
    messagingSenderId: '39354146251',
    projectId: 'petkart-74fec',
    storageBucket: 'petkart-74fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5fnLDMmiCVR9SAG8Qm0XtqyOVy80EPlI',
    appId: '1:39354146251:ios:c9e065d670398c64a76a4e',
    messagingSenderId: '39354146251',
    projectId: 'petkart-74fec',
    storageBucket: 'petkart-74fec.appspot.com',
    androidClientId: '39354146251-1h9kpltt9lkisr43gj261ams8o91ms0g.apps.googleusercontent.com',
    iosClientId: '39354146251-1modmm3a1mvlpeg6akbqelbiofdvl1pe.apps.googleusercontent.com',
    iosBundleId: 'com.petkartvendor.app.petkartVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnKrehqtrR5Op1H3rPRFX-RSbRFZ2wYLE',
    appId: '1:39354146251:web:bde5bc0515ee1566a76a4e',
    messagingSenderId: '39354146251',
    projectId: 'petkart-74fec',
    authDomain: 'petkart-74fec.firebaseapp.com',
    storageBucket: 'petkart-74fec.appspot.com',
    measurementId: 'G-8SKRR4HQ9E',
  );
}
